version: "3.9"

services:
  mqttbroker:
    platform: "linux/arm/v7"
  lightcontroller:
    platform: "linux/arm/v7"
    env_file:
      - ./.env.prod
  crontrigger:
    platform: "linux/arm/v7"
    env_file:
      - ./.env.prod
  triggersapi:
    platform: "linux/arm/v7"
  blecron:
    platform: "linux/arm/v7"
    image: "c4stus/raspberrypi:blecron"
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z
    env_file:
      - ./.env.prod
