version: "3.9"

services:
  mqttbroker:
    platform: "linux/arm/v7"
  lightcontroller:
    platform: "linux/arm/v7"
    env_file:
      - ./.env.prod
  crontrigger:
    platform: "linux/arm/v7"
    env_file:
      - ./.env.prod
  triggersapi:
    platform: "linux/arm/v7"
  blecron:
    platform: "linux/arm/v7"
    depends_on:
      - mqttbroker
    container_name: blecron
    image: "c4stus/raspberrypi:blecron"
    privileged: true
    networks:
      - mqtt-network
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z
    tty: true
    env_file:
      - ./.env
      - ./.env.prod
